# Run script

In [ ]:
# Install dependencies
!pip install nltk rouge-score sacrebleu bert-score

In [ ]:
# Import nltk and download punk_tab
import nltk
nltk.download("punkt_tab")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("omw-1.4")

In [ ]:
# Run script
!python run_movie_rag_eval.py

**Note:** Output was trunucated to avoid printing out model loading.
```
=== Corpus / Macro Results ===
Corpus BLEU: 0.0729
Avg Sentence BLEU: 0.0871
Avg ROUGE-1 F1: 0.3325
Avg ROUGE-2 F1: 0.1607
Avg ROUGE-L F1: 0.2714
Avg METEOR: 0.4255
Avg TER (lower is better): 302.4843
Avg ChrF: 39.6788
Avg BERTScore F1: 0.8861
```

# Add to query level data

In [25]:
# View dataframe
import pandas as pd
df = pd.read_csv("movie_rag_eval_results.csv")
df

,idx,query,bleu,rougeL,meteor,ter,chrf,bertscore_f1
0,1,What is the plot of The Hunger Games?,0.0325,0.1233,0.3133,752.0000,29.9329,0.8679
1,2,What happens at the end of Jaws: The Revenge?,0.3114,0.4638,0.5781,152.3810,51.1734,0.9236
2,3,What is Fletcher Reede’s main problem in Liar ...,0.1172,0.2857,0.5344,294.7368,43.5177,0.8956
3,4,Who is Horton and what does he discover in Hor...,0.2683,0.4000,0.6137,271.4286,56.3454,0.8978
4,5,What is the relationship between Mike and Marc...,0.1392,0.2828,0.4036,256.0000,45.6613,0.9057
5,6,What happens during Lizzie’s trip to Italy in ...,0.0119,0.1263,0.3040,665.2174,24.6169,0.8730
6,7,Which movie involves a group trying to stop a ...,0.0068,0.1606,0.2177,186.0465,29.0908,0.8523
7,8,Which movie involves a boxer rising from nothing?,0.0186,0.1957,0.3064,173.3333,24.2555,0.8746
8,9,What tragedy brings the women together in Stee...,0.1816,0.3860,0.5215,164.7059,49.6806,0.9023
9,10,What genre is Beauty and the Beast?,0.1033,0.6111,0.7194,123.0769,46.7034,0.9178
10,11,I'm hosting a family-friendly Halloween party ...,0.0052,0.1649,0.1937,157.1429,27.8882,0.8750
11,12,"In the movie 'No Country for Old Men', how doe...",0.0576,0.2308,0.4313,300.0000,33.1865,0.8730
12,13,"I'm looking for a fun, upbeat musical movie fo...",0.0656,0.2097,0.4895,376.0000,31.9455,0.8900
13,14,Can you tell me the name of the ancient sorcer...,0.2148,0.5143,0.7559,116.6667,69.4751,0.9292
14,15,My film club is doing a showcase on intense ps...,0.0102,0.1048,0.2135,895.0000,21.8815,0.8659
15,16,"According to the plot of 'The Incredibles', wh...",0.0173,0.3529,0.4222,200.0000,45.5984,0.8957
16,17,My friends and I want to turn our brains off a...,0.0113,0.1649,0.3888,206.0606,30.5433,0.8692
17,18,"In the movie 'Mad Max Beyond Thunderdome', wha...",0.2945,0.6286,0.7609,108.3333,66.8115,0.9252
18,19,We're having a horror movie marathon and want ...,0.0237,0.2766,0.3528,315.0000,38.6619,0.8976
19,20,"In the movie 'Forrest Gump', what are some of ...",0.0717,0.2092,0.4822,470.8333,42.3719,0.8585
20,21,What is a good movie about a young person movi...,0.0676,0.1781,0.3802,423.2558,34.8658,0.8687
21,22,What movie is about Jean Valjean being pursued...,0.1110,0.3729,0.5290,284.6154,52.5398,0.8873
22,23,What is a good action movie involving espionag...,0.0263,0.1871,0.3375,183.7209,39.0580,0.8666
23,24,What movie is about Michael Jordan teaming up ...,0.1023,0.2449,0.6421,300.0000,47.8746,0.8827
24,25,What is a horror movie about a group of friend...,0.0705,0.2034,0.2707,165.0000,39.3889,0.8755
25,26,What is a classic slasher movie set at a camp ...,0.1864,0.3259,0.3617,143.7500,43.9496,0.8969
26,27,What is a stylish crime movie involving a weal...,0.0192,0.2456,0.3776,395.2381,31.8480,0.8779
27,28,What’s the movie about a girl who wants to pla...,0.0080,0.1692,0.2459,450.0000,24.5788,0.8719
28,29,What’s the movie about FBI agents investigatin...,0.0333,0.1375,0.2760,377.4194,30.0566,0.8708
29,30,What is a sci-fi thriller about scientists try...,0.0257,0.1852,0.3415,167.5676,36.8621,0.8950

In [27]:
# Define list for precision
precision = [
    0.8, #1
    0.4, #2
    0.6, #3
    1.0, #4
    0.6, #5
    1.0, #6
    0.4, #7
    0.4, #8
    1.0, #9
    0.8, #10
    0.8, #11
    0.0, #12
    0.4, #13
    0.2, #14
    0.2, #15
    0.8, #16
    0.2, #17
    0.8, #18
    0.8, #19
    0.6, #20
    0.6, #21
    1.0, #22
    0.6, #23
    0.4, #24
    0.6, #25
    0.2, #26
    0.2, #27
    0.6, #28
    0.2, #29
    0.2, #30
]

In [28]:
latency = [
    32.77, #1
    9.34, #2
    10.67, #3
    13.27, #4
    8.95, #5
    26.23, #6
    7.64, #7
    16.66, #8
    11.65, #9
    4.6, #10
    4.33, #11
    4.33, #12
    4.33, #13
    4.33, #14
    24.54, #15
    11.07, #16
    11.25, #17
    5.72, #18
    11.90, #19
    28.18, #20
    12.0, #21
    17.0, #22
    36.0, #23
    10.0, #24
    16.0, #25
    15.0, #26
    10.0, #27
    16.0, #28
    20.0, #29
    8.0, #30
]

In [29]:
# Add to dataframe
df['precision'] = precision
df['latency'] = latency

In [31]:
# View result
df

,idx,query,bleu,rougeL,meteor,ter,chrf,bertscore_f1,precision,latency
0,1,What is the plot of The Hunger Games?,0.0325,0.1233,0.3133,752.0000,29.9329,0.8679,0.8,32.77
1,2,What happens at the end of Jaws: The Revenge?,0.3114,0.4638,0.5781,152.3810,51.1734,0.9236,0.4,9.34
2,3,What is Fletcher Reede’s main problem in Liar ...,0.1172,0.2857,0.5344,294.7368,43.5177,0.8956,0.6,10.67
3,4,Who is Horton and what does he discover in Hor...,0.2683,0.4000,0.6137,271.4286,56.3454,0.8978,1.0,13.27
4,5,What is the relationship between Mike and Marc...,0.1392,0.2828,0.4036,256.0000,45.6613,0.9057,0.6,8.95
5,6,What happens during Lizzie’s trip to Italy in ...,0.0119,0.1263,0.3040,665.2174,24.6169,0.8730,1.0,26.23
6,7,Which movie involves a group trying to stop a ...,0.0068,0.1606,0.2177,186.0465,29.0908,0.8523,0.4,7.64
7,8,Which movie involves a boxer rising from nothing?,0.0186,0.1957,0.3064,173.3333,24.2555,0.8746,0.4,16.66
8,9,What tragedy brings the women together in Stee...,0.1816,0.3860,0.5215,164.7059,49.6806,0.9023,1.0,11.65
9,10,What genre is Beauty and the Beast?,0.1033,0.6111,0.7194,123.0769,46.7034,0.9178,0.8,4.60
10,11,I'm hosting a family-friendly Halloween party ...,0.0052,0.1649,0.1937,157.1429,27.8882,0.8750,0.8,4.33
11,12,"In the movie 'No Country for Old Men', how doe...",0.0576,0.2308,0.4313,300.0000,33.1865,0.8730,0.0,4.33
12,13,"I'm looking for a fun, upbeat musical movie fo...",0.0656,0.2097,0.4895,376.0000,31.9455,0.8900,0.4,4.33
13,14,Can you tell me the name of the ancient sorcer...,0.2148,0.5143,0.7559,116.6667,69.4751,0.9292,0.2,4.33
14,15,My film club is doing a showcase on intense ps...,0.0102,0.1048,0.2135,895.0000,21.8815,0.8659,0.2,24.54
15,16,"According to the plot of 'The Incredibles', wh...",0.0173,0.3529,0.4222,200.0000,45.5984,0.8957,0.8,11.07
16,17,My friends and I want to turn our brains off a...,0.0113,0.1649,0.3888,206.0606,30.5433,0.8692,0.2,11.25
17,18,"In the movie 'Mad Max Beyond Thunderdome', wha...",0.2945,0.6286,0.7609,108.3333,66.8115,0.9252,0.8,5.72
18,19,We're having a horror movie marathon and want ...,0.0237,0.2766,0.3528,315.0000,38.6619,0.8976,0.8,11.90
19,20,"In the movie 'Forrest Gump', what are some of ...",0.0717,0.2092,0.4822,470.8333,42.3719,0.8585,0.6,28.18
20,21,What is a good movie about a young person movi...,0.0676,0.1781,0.3802,423.2558,34.8658,0.8687,0.6,12.00
21,22,What movie is about Jean Valjean being pursued...,0.1110,0.3729,0.5290,284.6154,52.5398,0.8873,1.0,17.00
22,23,What is a good action movie involving espionag...,0.0263,0.1871,0.3375,183.7209,39.0580,0.8666,0.6,36.00
23,24,What movie is about Michael Jordan teaming up ...,0.1023,0.2449,0.6421,300.0000,47.8746,0.8827,0.4,10.00
24,25,What is a horror movie about a group of friend...,0.0705,0.2034,0.2707,165.0000,39.3889,0.8755,0.6,16.00
25,26,What is a classic slasher movie set at a camp ...,0.1864,0.3259,0.3617,143.7500,43.9496,0.8969,0.2,15.00
26,27,What is a stylish crime movie involving a weal...,0.0192,0.2456,0.3776,395.2381,31.8480,0.8779,0.2,10.00
27,28,What’s the movie about a girl who wants to pla...,0.0080,0.1692,0.2459,450.0000,24.5788,0.8719,0.6,16.00
28,29,What’s the movie about FBI agents investigatin...,0.0333,0.1375,0.2760,377.4194,30.0566,0.8708,0.2,20.00
29,30,What is a sci-fi thriller about scientists try...,0.0257,0.1852,0.3415,167.5676,36.8621,0.8950,0.2,8.00

In [33]:
# Get aggregations
avg_precision = df['precision'].mean()
avg_latency = df['latency'].mean()

# print
print(f"Average Precision: {avg_precision:.2f}")
print(f"Average Latency: {avg_latency:.2f}")

Average Precision: 0.55
Average Latency: 13.73

In [35]:
# Save csv
df.to_csv("movie_rag_evaluation.csv", index=False)